
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #服务续约
    lease-expiration-duration-in-seconds: 10 #服务剔除>服务续约时间
#spring:
#  application:
#    name: trace-2