

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ley1996/spring-cloud-study.git
          search-paths: config-server
          username: ley1996
          password: ENC(Xlko242EkRvnpNdD4+H0Xr0ojA3ipJib)


server:
  port: 9099
management:
  security:
    enabled: false

#password encrypt
jasypt:
  encryptor:
    #encrypt key
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7