server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #服务续约
    lease-expiration-duration-in-seconds: 10 #服务剔除>服务续约时间

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: eureka-client-feign