
spring:
  application:
    name: stream-rabbit

  rabbitmq:
    host: softyuan.cn
    port: 5672
    username: root
    password: root

#消息反馈
  cloud:
    stream:
      bindings:
        input:
          destination: channel-b
        output:
          destination: channel-a
server:
  port: 9090
