server:
  port: 10011
spring:
  application:
    name: swagger-service-b


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

swagger:
  base-package: com.ley.springcloud.swagger
