server:
  port: 8704

spring:
  application:
    name: eureka-ribbon-hystrix
  cloud:
    circuit:
      breaker:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #服务续约
    lease-expiration-duration-in-seconds: 15 #服务剔除>服务续约时间
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost

#com.netflix.client.config.CommonClientConfigKey
ribbon:
  #eureka客户端ribbon刷新时间,默认30s
  ServerListRefreshInterval: 5000
logging:
  level:
    com:
      netflix:
       hystrix: debug
      ley:
        springcloud:  debug
management:
  security:
    enabled: false


