server:
  port: 9001

spring:
  application:
    name: eureka-ribbon-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    #eureka client刷新本地缓存时间,默认30s
    registry-fetch-interval-seconds: 5

#com.netflix.client.config.CommonClientConfigKey
ribbon:
  #eureka客户端ribbon刷新时间,默认30s
  ServerListRefreshInterval: 5000