server:
  port: 9002

spring:
  application:
    name: ribbon-client

#let Eureka ribbon 失效
ribbon:
  eureka:
    enabled: false

eureka-provider:
  ribbon:
    ConnectTimeout: 250 #单位ms,请求连接超时时间
    ReadTimeout: 1000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
    #单独使用Ribbon,传统的注册(没有和Eureka结合)
    listOfServers: localhost:1606,localhost:1727
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule