
#spring cloud sleuth 整合 spring cloud sleuth zipkin
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #服务续约
    lease-expiration-duration-in-seconds: 10 #服务剔除>服务续约时间
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1
  application:
    name: trace-1
